name: Build for Windows
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -G "Visual Studio 16 2019" -A x64 -B "./build" .
      - name: Upload Artifact to GitHub Action
        uses: actions/upload-artifact@v4
        with:
          path: build/*
          name: Sandbox
